// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHILiIBA9FevMJISkzZdw2AmmjvML7GI0',
    appId: '1:766305547317:web:10dbee7b313c4cde3aed7c',
    messagingSenderId: '766305547317',
    projectId: 'user-crud-f9f6e',
    authDomain: 'user-crud-f9f6e.firebaseapp.com',
    storageBucket: 'user-crud-f9f6e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx5lZy5qDRBTpysymDUZkU33rqstROdIM',
    appId: '1:766305547317:android:304dca025aab2f853aed7c',
    messagingSenderId: '766305547317',
    projectId: 'user-crud-f9f6e',
    storageBucket: 'user-crud-f9f6e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClSbZ4Q2DWAg5ShJcY8_ag4PntelWACIE',
    appId: '1:766305547317:ios:37eedc21557942f83aed7c',
    messagingSenderId: '766305547317',
    projectId: 'user-crud-f9f6e',
    storageBucket: 'user-crud-f9f6e.appspot.com',
    iosClientId: '766305547317-ddihmpb1qlifqj0sb7brmrma9jvbfvsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.userCrud',
  );
}
